name: Cybers Athletic
author: Cybers Athletic
baseurl: /Desafios
description: 
github: http://www.github.com/cybers-athletic
twitter: http://www.twitter.com/atleticacybers
facebook: http://www.facebook.com/atleticacybers
linkedin: http://www.linkedin.com/atleticacybers
email: contato[at]cybers-athletic.club
location: 42°2'16"N   70°12'47"W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
